# .github/workflows/ci.yml
name: CI for Node.js and FastAPI

on:
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      # 1. 코드 체크아웃
      - name: Checkout code
        uses: actions/checkout@v3

      #  Build and run FastAPI service
      - name: Build FastAPI service
        run: docker build -t fastapi-service ./model

      #  Build and run nodejs service
      - name: Build NodeJs service
        run: docker build -t nodejs-service ./backend

      - name: Run FastAPI service
        run: |
          docker run -d --name fastapi-container -p 8000:8000 -v ${{ github.workspace }}/test/fastapi_test:/app/test fastapi-service

      - name: Run nodejs service
        run: |
          docker run -d --name nodejs-container -p 3000:3000 \
            -v ${{ github.workspace }}/test/nodejs_test:/app/test \
            -e DB_USER=${{ secrets.DB_USER }} \
            -e DB_PASSWORD=${{ secrets.DB_PASSWORD }} \
            -e DB_HOST=${{ secrets.DB_HOST }} \
            -e DB_NAME=${{ secrets.DB_NAME }} \
            nodejs-service

      #  Wait for FastAPI service to be ready (Optional)
      - name: Wait for FastAPI service to be ready
        run: sleep 10 # 필요한 경우 이 값을 조정하여 서비스 시작 시간 고려

      #  Run FastAPI tests
      - name: Run FastAPI tests
        run: docker exec fastapi-container pytest test/

      #  Run Nodejs tests
      - name: Run NodeJS tests
        run: docker exec nodejs-container npm test

      - name: Print success message
        if: success()
        run: echo "All tests passed successfully!"

      #  Tear down Node.js and FastAPI containers
      - name: Stop and remove Node.js and FastAPI containers
        if: always()
        run: |
          docker stop fastapi-container
          docker rm fastapi-container
          docker stop nodejs-container
          docker rm nodejs-container
